const PING = 'PING';
const PONG = 'PONG';
const UNKNOWN = 'UNKNOWN';
const BEGIN_API_1_CALL = 'BEGIN_API_1_CALL';
const BEGIN_API_2_CALL = 'BEGIN_API_2_CALL';
const BEGIN_API_3_CALL = 'BEGIN_API_3_CALL';

export default {
    PING, 
    PONG,
    UNKNOWN,
    BEGIN_API_1_CALL,
    BEGIN_API_2_CALL,
    BEGIN_API_3_CALL
}